--------------------------------------------------
CREATE TABLE BANK_ACCOUNT_TYPES (
	ACCOUNT_TYPE_ID CHAR(10),
	ACCOUNT_TYPE_LABEL VARCHAR(50),
	--
	PRIMARY KEY (ACCOUNT_TYPE_ID)
);

--------------------------------------------------
CREATE TABLE BANK_NAMES (
	BANK_NAME_ID CHAR(10),
	BANK_NAME_LABEL VARCHAR(50),
	--
	PRIMARY KEY (BANK_NAME_ID)
);

--------------------------------------------------
CREATE TABLE CLIENTS_BANK_ACOUNTS (
	CLIENT_ACCOUNT_TYPE_ID CHAR(10),
	CLIENT_BANK_NAME_ID CHAR(10),
	BANK_ACCOUNT_NUMBER CHAR(10),
	CLIENT_NAME VARCHAR(128),
	--
	PRIMARY KEY (CLIENT_ACCOUNT_TYPE_ID, CLIENT_BANK_NAME_ID, BANK_ACCOUNT_NUMBER),
	FOREIGN KEY (CLIENT_ACCOUNT_TYPE_ID) REFERENCES BANK_ACCOUNT_TYPES (ACCOUNT_TYPE_ID),
	FOREIGN KEY (CLIENT_BANK_NAME_ID) REFERENCES BANK_NAMES (BANK_NAME_ID)
);
